name: Package

on:
  push:
    branches:
      - master

jobs:
  build-upload-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build project
        run: npm install && npm run build
      
      - name: Deploy Tencent Cloud COS
        uses: egcn/actions-coscmd@v1
        with:
          args: upload -rs --delete ./public/ / --ignore .git
          secret_id: ${{ secrets.SECRET_ID }}
          secret_key: ${{ secrets.SECRET_KEY }}
          bucket: ${{ secrets.BUCKET }}
          region: ${{ secrets.REGION }}